### ISSUE TITLE
电影评分数据明显不足

### ISSUE THREAD

**Issue by WangHexie** [csuldw/AntSpider#3]
很多经典或是热门电影，大的那个数据集里就没有。 像是盗梦空间，电影数据集里信息缺失，评分一条都没。豆瓣top 200里很多都找不到。     
每部电影的评分数量也是明显不足的，最多一部电影才四百多个评分。
这点也可以从用户评分上看出，一般用户只有一条评分，基本上就没有什么用。   
   
是否还有更完整的更大的数据集能够释出？   
我看readme里有些说，电影评价最多只能看两百多条，是否能从用户上下手？我看用户评价退出账号后，一千多条都能看

**Comment by csuldw** [comment]
这个评分数据相当于采样得到，仅做参考，要想把全部的评分数据怕取出来，还是有一定的困难，你如果有这个想法，可以试试。------------------ 原始邮件 ------------------发件人: WangHexie  <notifications@github.com>发送时间: 2020年1月29日 10:58收件人: csuldw/AntSpider <AntSpider@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[csuldw/AntSpider] 电影评分数据明显不足 (#3)很多经典或是热门电影，大的那个数据集里就没有。 像是盗梦空间，电影数据集里信息缺失，评分一条都没。豆瓣top 200里很多都找不到。
每部电影的评分数量也是明显不足的，最多一部电影才四百多个评分。
这点也可以从用户评分上看出，一般用户只有一条评分，基本上就没有什么用。
是否还有更完整的更大的数据集能够释出？
我看readme里有些说，电影评价最多只能看两百多条，是否能从用户上下手？我看用户评价退出账号后，一千多条都能看

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/csuldw/AntSpider/issues/3?email_source=notifications\u0026email_token=AC4247ZL7Q463MYENKPDBE3RADWFFA5CNFSM4KM5ZC3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IJNE6GA",
"url": "https://github.com/csuldw/AntSpider/issues/3?email_source=notifications\u0026email_token=AC4247ZL7Q463MYENKPDBE3RADWFFA5CNFSM4KM5ZC3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IJNE6GA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
